Models/Chef.cs
#pragma warning disable CS8618
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace _5_Chefs_N_Dishes.Models;

public class Chef
{
    [Key]
    public int ChefId {get;set;}

    [Required]
    [Display(Name = "First Name")]
    public string FirstName {get;set;}
    [Required]
    [Display(Name = "Last Name")]
    public string LastName {get;set;}
    [Required]
    [DateMinimumAge(18, ErrorMessage = "Chef must be at least 18 years old")]
    [Display(Name = "Date of Birth")]
    public DateTime DOB {get;set;}

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    public List<Dish> AllDishes {get;set;} = new List<Dish>();
    
}
public class DateMinimumAgeAttribute : ValidationAttribute
{
    public DateMinimumAgeAttribute(int minimumAge)
    {
        MinimumAge = minimumAge;
    }

    public override bool IsValid(object value)
    {
        DateTime date;
        if ((value != null && DateTime.TryParse(value.ToString(), out date)))
        {
            return date.AddYears(MinimumAge) < DateTime.Now;
        }

        return false;
    }

    public int MinimumAge { get; }
}

Models/Dish.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace _5_Chefs_N_Dishes.Models;

public class Dish
{
    [Key]
    public int DishId {get;set;}

    [Required]
    [MinLength(2, ErrorMessage = "Name must be at least 2 chars")]
    public string Name {get;set;}
    
    [Required]
    [Range(0, Int32.MaxValue, ErrorMessage = "Calories must be greater than 0")]
    public int Calories {get;set;}

    [Required]
    [Range(1, 6, ErrorMessage = "Tastiness must be between 1 and 5")]
    public int Tastiness {get;set;}

    public DateTime CreatedAt {get;set;} = DateTime.Now;
    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    [Required]
    [Display(Name = "Chef's Name")]
    public int ChefId {get;set;}
    public Chef? Creator {get;set;}
}

Models/ErrorViewModel.cs
namespace _5_Chefs_N_Dishes.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MyContext.cs
#pragma warning disable CS8618
using Microsoft.EntityFrameworkCore;
namespace _5_Chefs_N_Dishes.Models;
public class MyContext : DbContext 
{   
    public MyContext(DbContextOptions options) : base(options) { }
    
    public DbSet<Chef> Chefs { get; set; } 
    public DbSet<Dish> Dishes { get; set; } 
}

Controllers/ChefController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _5_Chefs_N_Dishes.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;

namespace _5_Chefs_N_Dishes.Controllers;

public class ChefController : Controller
{
    private readonly ILogger<ChefController> _logger;
    public MyContext db;

    public ChefController(ILogger<ChefController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("chefs")]
    public IActionResult Index()
    {
        List<Chef> allChefs = db.Chefs.Include(d => d.AllDishes).ToList();
        return View(allChefs);
    }

    [HttpGet("chefs/new")]
    public IActionResult New()
    {
        return View();
    }

    [HttpPost("chefs/create")]
    public IActionResult Create(Chef newChef)
    {
        if (!ModelState.IsValid)
        {
            return View("New");
        }
        db.Chefs.Add(newChef);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _5_Chefs_N_Dishes.Models;
using Microsoft.EntityFrameworkCore;

namespace _5_Chefs_N_Dishes.Controllers;

public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;
    public MyContext db;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("dishes")]
    public IActionResult Index()
    {
        List<Dish> allDishes = db.Dishes.Include(c => c.Creator).OrderBy(c => c.CreatedAt).ToList();
        return View(allDishes);
    }

    [HttpGet("dishes/new")]
    public IActionResult New()
    {
        ViewBag.allChefs = db.Chefs.ToList();
        return View();
    }

    [HttpPost("dishes/create")]
    public IActionResult Create(Dish newdish)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.allChefs = db.Chefs.ToList();
            return View("New");
        }
        db.Dishes.Add(newdish);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _5_Chefs_N_Dishes.Models;

namespace _5_Chefs_N_Dishes.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Chef/Index.cshtml
@{
    ViewData["Title"] = "Chefs";
}
@model List<Chef>
<div class="text-center">
    @await Html.PartialAsync("_Navbar")
    <h1 class="display-4 border-bottom">Check out our roster of chefs!</h1>
    <hr>
    
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th># of Dishes</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Chef c in Model)
            {
            <tr>
                <td>@c.FirstName @c.LastName</td>
                <td>@(DateTime.Now.Year - c.DOB.Year)</td>
                <td>@c.AllDishes.Count</td>
            </tr>
            }
        </tbody>
    </table>
</div>

Views/Chef/New.cshtml
@{ViewData["Title"] = "Add a Chef";}
@await Html.PartialAsync("_Navbar")
@model Chef
<h1 class="text-center">Add a Chef</h1>
<hr>
<form asp-controller="Chef" asp-action="Create" method="post" class="d-flex flex-column gap-3">
    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" type="text"><br>
        <span asp-validation-for="FirstName" class="text-danger font-weight-bold"></span>
    </div>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" type="text"><br>
        <span asp-validation-for="LastName" class="text-danger font-weight-bold"></span>
    </div>
    <div>
        <label asp-for="DOB"></label>
        <input asp-for="DOB" type="date"><br>
        <span asp-validation-for="DOB" class="text-danger font-weight-bold"></span>
    </div>
    <div>
        <button class="btn btn-outline-dark">Submit</button>
    </div>
</form>

Views/Dish/Index.cshtml
@{
    ViewData["Title"] = "Dishes";
}
@model List<Dish>
<div class="text-center">
    @await Html.PartialAsync("_Navbar")
    <h1 class="display-4">Yum! Check out our tasty dishes!</h1> <hr>
    
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Chef</th>
                <th>Tastiness</th>
                <th>Calories</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Dish d in Model)
            {
            <tr>
                <td>@d.Name</td>
                <td>@d.Creator.FirstName @d.Creator.LastName</td>
                <td>@d.Tastiness</td>
                <td>@d.Calories</td>
            </tr>
            }
        </tbody>
    </table>
</div>

Views/Dish/New.cshtml
@{ViewData["Title"] = "Add a Dish";}
@await Html.PartialAsync("_Navbar")
@model Dish
<h1 class="text-center">Add a Dish</h1>
<hr>
<form asp-controller="Dish" asp-action="Create" method="post">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-column">
            <div class="d-flex flex-column">
                <div class="d-flex justify-content-between gap-2">
                    <label asp-for="Name"></label>
                    <span asp-validation-for="Name" class="text-danger font-weight-bold"></span>
                </div>
                <input asp-for="Name" type="text">
            </div>
            <div class="d-flex flex-column">
                <div class="d-flex justify-content-between gap-2">
                    <label asp-for="Calories"></label>
                    <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
                </div>
                <input asp-for="Calories" type="text">
            </div>
        </div>
        <div>
            <label asp-for="ChefId"></label><br>
            <span asp-validation-for="Tastiness" class="text-danger font-weight-bold"></span>
            <select asp-for="ChefId">
                <option value="" selected disabled>-- Select a Chef --</option>
                @foreach(Chef c in ViewBag.allChefs)
                {
                <option value="@c.ChefId">@c.FirstName @c.LastName</option>
                }
            </select>
        </div>
        <div>
            <label asp-for="Tastiness"></label><br>
            <span asp-validation-for="Tastiness" class="text-danger font-weight-bold"></span>
            <select asp-for="Tastiness">
                <option value="" selected disabled>--Select Tastiness--</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
    </div>
    <div class="d-flex justify-content-end">
        <button class="btn btn-outline-dark">Submit</button>
    </div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @ViewData["Title"]!</h1>
    <p>Let's get started!</p>
    <p>Click on a link above to check out the Chefs or their Dishes!</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chefs N Dishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_5_Chefs_N_Dishes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chefs N Dishes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chef" asp-action="Index">Chefs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Index">Dishes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Chefs N Dishes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<div class="d-flex justify-content-center gap-3">
    @if(ViewData["Title"] == "Chefs")
    {
        <p>Chefs</p>
    }else
    {
        <a asp-controller="Chef" asp-action="Index">Chefs</a>
    }
    |
    @if(ViewData["Title"] == "Dishes")
    {
        <p>Dishes</p>
    }else
    {
        <a asp-controller="Dish" asp-action="Index">Dishes</a>
    }
    |
    @if(ViewData["Title"] == "Add a Chef")
    {
        <p>Add a Chef</p>
    }else
    {
        <a asp-controller="Chef" asp-action="New">Add a Chef</a>
    }
    |
    @if(ViewData["Title"] == "Add a Dish")
    {
        <p>Add a Dish</p>
    }else
    {
        <a asp-controller="Dish" asp-action="New">Add a Dish</a>
    }
</div>